name: Deploy Spring Boot to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./simpleproject

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "19"

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        env:
          AWS_DB_HOST: ${{ secrets.AWS_DB_HOST }}
          AWS_DB_USERNAME: ${{ secrets.AWS_DB_USERNAME }}
          AWS_DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
        run: ./gradlew build

      - name: Upload jar file to artifact
        uses: actions/upload-artifact@v3
        with:
          name: BackendApplication
          path: build/libs/simpleproject-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: self-hosted
    needs: build-and-upload

    steps:
      - name: Delete old jar file
        run: rm -rf /home/ubuntu/backend/build/*.jar

      - name: Download jar file from artifact
        uses: actions/download-artifact@v3
        with:
          name: BackendApplication
          path: /home/ubuntu/backend/build/

      - name: 배포하기
        run: sh /home/ubuntu/backend/deploy.sh
